name: Build and Release EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ps2exe
        run: Install-Module -Name ps2exe -Scope CurrentUser -Force -AllowClobber -Confirm:$false

      - name: Compile EXE
        run: |
          Import-Module ps2exe
          Invoke-PS2EXE .\Universal-KMS.ps1 .\Universal-KMS.exe -noConsole

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
          files: Universal-KMS.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
