name: Build and Release EXE

on:
  workflow_dispatch:   # позволяет запускать вручную
  push:
    branches:
      - main           # запуск при пуше в main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ps2exe
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module -Name ps2exe -Scope CurrentUser -Force -AllowClobber -Confirm:$false

      - name: Compile EXE
        run: |
          Import-Module ps2exe
          Invoke-PS2EXE .\Universal-KMS.ps1 .\Universal-KMS.exe -noConsole

      - name: Create Release and Upload EXE
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          files: Universal-KMS.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
